### Obtener todos los ejercicios
GET http://localhost:3000/api/ejercicios

### Obtener uno
GET http://localhost:3000/api/ejercicios/1

### Eliminar uno
DELETE http://localhost:3000/api/ejercicios/1

### Obtener todos los grupos musculares

GET http://localhost:3000/api/grupo_muscular

### Obtener todos alimentacion

GET http://localhost:3000/api/alimentacion

### Obtener todos los Entrenamientos

GET http://localhost:3000/api/entrenamientos